Repository muhBR/muh, pull requests merged in 2021-01, with the labels that each got.

#25 ✅ Add specs when user data is invalid
  backend/app/graphql/mutations/create_user.rb
  backend/spec/mutations/create_user_spec.rb
Labels: rails, test

#30 🔧 improve rails config env
  backend/app/helpers/json_web_token_helper.rb
  backend/config/initializers/env_check_initializer.rb
  docker-compose.yml
Labels: rails

#34 ✅ update graphql tests
  backend/spec/mutations/create_user_spec.rb
  backend/spec/rails_helper.rb
  backend/spec/support/graphql_helper.rb
Labels: rails, test

#32 Rails user login
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/graphql/mutations/sign_in.rb
  backend/app/graphql/types/mutation_type.rb
  backend/spec/factories/users.rb
  backend/spec/mutations/sign_in_spec.rb
  backend/spec/rails_helper.rb
  backend/spec/support/factory_bot.rb
Labels: rails

#43 ✅ improve sign in spec
  backend/app/graphql/types/base_union.rb
  backend/spec/mutations/create_user_spec.rb
  backend/spec/mutations/sign_in_spec.rb
Labels: rails, test

#44 Create category
  backend/app/controllers/graphql_controller.rb
  backend/app/graphql/mutations/create_category.rb
  backend/app/graphql/types/category_type.rb
  backend/app/graphql/types/mutation_type.rb
  backend/app/helpers/json_web_token_helper.rb
  backend/app/models/category.rb
  backend/db/migrate/20210114200829_create_categories.rb
  backend/db/schema.rb
  backend/spec/factories/categories.rb
  backend/spec/models/category_spec.rb
  backend/spec/mutations/create_category_spec.rb
  backend/spec/rails_helper.rb
  backend/spec/support/graphql_helper.rb
Labels: rails

#46 Add query to get categories
  README.md
  backend/app/controllers/application_controller.rb
  backend/app/controllers/graphql_controller.rb
  backend/app/graphql/queries/base_query.rb
  backend/app/graphql/queries/fetch_categories.rb
  backend/app/graphql/types/category_type.rb
  backend/app/graphql/types/query_type.rb
  backend/spec/queries/fetch_category_spec.rb
Labels: rails

#47 Update README.md
  README.md
Labels: documentation

#51 backend create item
  backend/app/controllers/application_controller.rb
  backend/app/controllers/graphql_controller.rb
  backend/app/graphql/mutations/create_item.rb
  backend/app/graphql/mutations/delete_item.rb
  backend/app/graphql/mutations/update_item.rb
  backend/app/graphql/queries/fetch_item.rb
  backend/app/graphql/queries/fetch_items.rb
  backend/app/graphql/types/item_type.rb
  backend/app/graphql/types/mutation_type.rb
  backend/app/graphql/types/query_type.rb
  backend/app/models/category.rb
  backend/app/models/item.rb
  backend/app/models/user.rb
  backend/db/migrate/20210118194736_create_items.rb
  backend/db/schema.rb
  backend/spec/factories/items.rb
  backend/spec/models/category_spec.rb
  backend/spec/models/item_spec.rb
  backend/spec/models/user_spec.rb
  backend/spec/mutations/create_item_spec.rb
  backend/spec/mutations/delete_item_spec.rb
  backend/spec/mutations/update_item_spec.rb
  backend/spec/queries/fetch_item_spec.rb
  backend/spec/queries/fetch_items_spec.rb
  docker-compose.yml
Labels: rails

#74 backend - Create service order
  backend/app/graphql/mutations/service_order/create_service_order.rb
  backend/app/graphql/types/input/base_input_object.rb
  backend/app/graphql/types/input/item_service_order_input.rb
  backend/app/graphql/types/model/item_service_order_type.rb
  backend/app/graphql/types/model/service_order_type.rb
  backend/app/graphql/types/mutation_type.rb
  backend/app/models/customer.rb
  backend/app/models/item.rb
  backend/app/models/item_service_order.rb
  backend/app/models/service_order.rb
  backend/app/models/user.rb
  backend/config/initializers/dates.rb
  backend/db/migrate/20210124073829_create_service_orders.rb
  backend/db/migrate/20210124082454_create_item_service_orders.rb
  backend/db/schema.rb
  backend/spec/factories/item_service_orders.rb
  backend/spec/factories/items.rb
  backend/spec/factories/service_orders.rb
  backend/spec/factories/users.rb
  backend/spec/models/customer_spec.rb
  backend/spec/models/item_service_order_spec.rb
  backend/spec/models/item_spec.rb
  backend/spec/models/service_order_spec.rb
  backend/spec/models/user_spec.rb
  backend/spec/mutations/service_order/create_service_order_spec.rb
  backend/spec/support/graphql_helper.rb
Labels: rails

#79 config coverage on code climate
  .codeclimate.yml
  .gitignore
  .semaphore/semaphore.yml
  README.md
  backend/Gemfile
  backend/Gemfile.lock
  generate_codeclimate_coverage.sh
Labels: CI/CD, rails, test

#69 Introducing apollo service configuration
  frontend/package.json
  frontend/src/pages/_app.tsx
  frontend/src/pages/signin/index.tsx
  frontend/src/services/apollo.ts
  frontend/yarn.lock
Labels: frontend
